name = "pluv-example-server-dev"
main = "dist/index.js"
compatibility_date = "2023-05-21"
node_compat = true

[durable_objects]
bindings = [
	{ name = "rooms", class_name = "RoomDurableObject" },
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "pluv_example_db"
database_id = "b7a7bdb4-7514-4d35-9992-4e0928194ee9"
